### ISSUE TITLE
Create Hops Async Component 

### ISSUE THREAD

**Issue by sbaer** [mcneel/compute.rhino3d#326]
Create new hops component that doesn’t wait for solves to complete. Review speckle’s “less janky” components article to see if we can use anything from it. https://speckle.systems/blog/async-gh/

The component should also provide two standard outputs
- complete (true/false)
- Progress (0.00->1.00): use the number of iterations and completed tasks to compute progress

**Comment by deKlerk** [comment]
@sbaer , maybe **FastAPI** would be a more adequate framework to deal with async, as an alternative to Flask: [https://fastapi.tiangolo.com/](https://fastapi.tiangolo.com/)
