### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by gerardsimons** [mcneel/compute.rhino3d#330]
Hi there,

Trying to run using Docker on Windows 10 with the following command:

`docker build -t compute-rhino .` 

Gives me the following error. (I am actually getting a similar output on Mac). Any idea what I am doing wrong? Thank you very much !

```
[+] Building 0.2s (4/4) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 34B                                                                                   0.0s
 => ERROR [internal] load metadata for mcr.microsoft.com/windows:1809                                              0.2s
 => CANCELED [internal] load metadata for mcr.microsoft.com/dotnet/framework/sdk:4.8                               0.2s
------
 > [internal] load metadata for mcr.microsoft.com/windows:1809:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:b89cd1aa06c5b27d72fb92c9a36bb5ab269ce6c8d9002732379d5726f031158e: not found
```

**Comment by gerardsimons** [comment]
Ah further research led me down the path of having to use `--isolation=process`, but this results in the following error:

```
Error response from daemon: Unsupported isolation: "process"
ERRO[0000] Can't add file /<PROJECT_PATH>/compute.rhino3d/.git/objects/pack/pack-2fe69ec8a2b019fecccd976e1cef3dea546aaa1a.pack to tar: io: read/write on closed pipe 
```

**Comment by pearswj** [comment]
This Dockerfile can only be built on a Windows computer and the "build" version (1809, 1909, etc.) of the host OS, [must match the base image](https://github.com/mcneel/compute.rhino3d/blob/bd95828078d43f21cae40e5475ae74e7ae168802/Dockerfile#L17). "Process" isolation is required (Rhino doesn't install correctly without it) and is supported in both Docker Desktop (Windows 10) and Docker EE (Windows Server).

Check which version of Windows you're using (see "System Settings" > "About") and update the windows image tag to match your OS, i.e. `FROM mcr.microsoft.com/windows:1909` (comment out the .NET 4.8 step if >1809) and then run...
```
docker build --isolation=process -t some-cool-name .
```

The current windows version number in the Dockerfile (1809) matches the version of Windows Server 2019 LTSC that most cloud container hosts use - unfortunately this means you also need a Windows Server 2019 host to build the image.

More info here... https://discourse.mcneel.com/t/docker-support/89322

**Comment by pearswj** [comment]
p.s. a couple of the steps in the Dockerfile had broken recently due to changes in compute.sln. I just pushed a fix!

**Comment by gerardsimons** [comment]
Ok, that is good to know, thank you! 

I was not aware of the strict requirements of specific build versions. In that case I do not really get the point of using Docker for this? Wasn't the purpose of it to allow you to more easily deploy it regardless of host OS or at least Windows 7/10/ ... or is that more of a legal / licensing issue with Windows? 

In any case I don't have Windows Server available to test with, but I think some added documentation on building it with Docker would be nice for future users!
