### ISSUE TITLE
Improve Error Message with definition running on compute that is not structured correctly

### ISSUE THREAD

**Issue by sbaer** [mcneel/compute.rhino3d#332]
The attached definition is using a group on a component to define an output. This is not supported yet. Until this feature is supported, we need to provide better error messages about what went wrong.
"Unable to Solve on Compute" is too generic of an error message
[Test-Hops-Plane.zip](https://github.com/mcneel/compute.rhino3d/files/6306081/Test-Hops-Plane.zip)

**Comment by pearswj** [comment]
We could use a better error message here too...

https://github.com/mcneel/compute.rhino3d/blob/c8bb22dc58658c2c00355261c5821b2a8a1e4a0a/src/compute.geometry/GrasshopperDefinition.cs#L779-L780

**Comment by sbaer** [comment]
No longer relevant as we now support components as output
