### ISSUE TITLE
Line.PointAt Method

### ISSUE THREAD

**Issue by mirkomaga** [mcneel/compute.rhino3d#453]
Hello,
I wanted to get a point on the curve, but if I invert the curve, isn't the result wrong? pnt2 shouldn't be 100; 100?

`Curve line = new LineCurve(new Line(0,0,0,100,100,0));`
`Point3d pnt1 = line.PointAt(0);`
`line.Reverse();`
`Point3d pnt2 = line.PointAt(0);`

![image](https://user-images.githubusercontent.com/56160646/151515624-d63633d1-0724-4ad5-ae3c-42595da8c09c.png)

**Comment by piac** [comment]
Our API has a https://developer.rhino3d.com/api/RhinoCommon/html/M_Rhino_Geometry_Line_Flip.htm Line.Flip() method.
That Reverse is likely an extension method from LINQ or some other library. Check its return type.

**Comment by mirkomaga** [comment]
Ok for Line, but for Arc?

**Comment by mirkomaga** [comment]
> Our API has a https://developer.rhino3d.com/api/RhinoCommon/html/M_Rhino_Geometry_Line_Flip.htm Line.Flip() method. That Reverse is likely an extension method from LINQ or some other library. Check its return type.


I think it does not go anyway.
The line remains with the same points.


![image](https://user-images.githubusercontent.com/56160646/151522376-61b6da7b-b198-4877-a719-1180f046feae.png)

**Comment by piac** [comment]
Please investigate more about ValueTypes. The returned value type internal to a class is immediately lost if you operate on it. That means that linecurve.Line.Flip() does nothing. LineCurve, on the other hand, has a https://developer.rhino3d.com/api/RhinoCommon/html/M_Rhino_Geometry_Curve_Reverse.htm a `Reverse()` method inherited from Curve. That one will work on the curve. Arc has a Reverse method as well, https://developer.rhino3d.com/api/RhinoCommon/html/M_Rhino_Geometry_Arc_Reverse.htm and ArcCurve inherits the Reverse method from Curve as well.

**Comment by mirkomaga** [comment]
> 

I am always of the opinion that the point on the curve at parameter 0 should be the final point after inverting the curve.

**Comment by piac** [comment]
@mirkomaga please post a sample that you think doesn't work, then we can see.
