### ISSUE TITLE
AppVeyor Artifacts missing

### ISSUE THREAD

**Issue by peterjgrainger** [mcneel/compute.rhino3d#547]
The Artifact https://ci.appveyor.com/api/projects/mcneel/compute-rhino3d/artifacts/compute.zip?branch=master is no longer available for download. I think the assets are deleted after a certain amount of time.

**Comment by fraguada** [comment]
Hello @peterjgrainger. That was part of an older CI pipeline. We have since changed that and recommend users follow this guide: https://developer.rhino3d.com/guides/compute/deploy/

**Comment by peterjgrainger** [comment]
@fraguada - here: https://developer.rhino3d.com/guides/compute/deploy/

**Comment by peterjgrainger** [comment]
Oh, and thanks!
