### ISSUE TITLE
Rhino 8 Compute

### ISSUE THREAD

**Issue by mdjaere** [mcneel/compute.rhino3d#630]
This isn't an issue but rather an appreciation of the excellent progress happening at McNeel. I've tested Rhino 8, and the new features are excellent!

I haven't followed the work on the 8.x branch, but now that Rhino 8 is out, can we expect to be able to run it on the server? Will there be any new features?

Many thanks!

**Comment by sbaer** [comment]
@andyopayne recently updated our guide for deploying a Rhino 8 based version of compute (https://developer.rhino3d.com/guides/compute/deploy-to-iis/)

This new version of compute was a rewrite to be based on .NET 7 ASP.NET technology. We haven't added any other "new features" specifically to compute yet, but you do have access to all of the new functionality in RhinoCommon for Rhino 8
https://developer.rhino3d.com/api/rhinocommon/whatsnew/8.0
